name=MaxBot
version=1.0.0
author=YarikG <union2003@yandex.ru>
maintainer=YarikG <union2003@yandex.ru>
sentence=A fast library for Max messenger bots on ESP32/ESP8266.
paragraph=Supports inline keyboards, OTA updates, and manual JSON parsing.
category=Communication
url=https://github.com/YarikGITSH777/MaxBotESP
architectures=esp32,esp8266
includes=MaxBot.h
